-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 07:35:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Heaven_Gebregiorgis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Heaven_Gebregiorgis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Heaven_Gebregiorgis` DEFAULT CHARACTER SET utf8 ;
USE `Heaven_Gebregiorgis` ;

-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Communication_Preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Communication_Preferences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_notification` ENUM('Allow', 'Do not allow') NOT NULL,
  `text` ENUM('Send', 'Do not send') NOT NULL,
  `email` ENUM('Yes', 'No') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` ENUM('On', 'Off') NOT NULL,
  `advertising_preference` ENUM('EveryDay', 'Once a week', 'Do not send') NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `camera_permission` ENUM('Allow', 'Do not allow') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registered_on` DATETIME NOT NULL,
  `last_Login` DATETIME NOT NULL,
  `communication_preference_id` INT NOT NULL,
  `setting_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Communication_Preferences1_idx` (`communication_preference_id` ASC) VISIBLE,
  INDEX `fk_Users_Settings1_idx` (`setting_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Communication_Preferences1`
    FOREIGN KEY (`communication_preference_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Communication_Preferences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_Settings1`
    FOREIGN KEY (`setting_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `house_number` INT NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `apartment_number` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department` ENUM('Clothes', 'Shoes', 'Home', 'Electronics') NOT NULL,
  `grouping` ENUM('Men', 'Women', 'Kids', 'Babies') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Vendors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vendor_name` VARCHAR(45) NOT NULL,
  `contact_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vendors_Addresses1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vendors_Addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `size` NVARCHAR(10) NOT NULL,
  `status` ENUM('In stck', 'Sold out') NOT NULL,
  `category_id` INT NOT NULL,
  `vendor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_Categories1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_Products_Vendors1_idx` (`vendor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Vendors1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Vendors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `total_items` INT NOT NULL,
  `total_price` DECIMAL(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Carts_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Carts_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_details` MULTILINESTRING NOT NULL,
  `total_price` DECIMAL(45) NOT NULL,
  `placed_at` DATETIME NOT NULL,
  `confirmation_number` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Wallets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Wallets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_number` VARCHAR(45) NOT NULL,
  `card_expiration` DATE NOT NULL,
  `security_code` INT NOT NULL,
  `rewards` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Wallets_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Wallets_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Order_id` INT NOT NULL,
  `Wallet_id` INT NOT NULL,
  `transactionStatus` ENUM('Posted', 'Pending') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transactions_Orders_idx` (`Order_id` ASC) VISIBLE,
  INDEX `fk_Transactions_Wallets1_idx` (`Wallet_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions_Orders`
    FOREIGN KEY (`Order_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Transactions_Wallets1`
    FOREIGN KEY (`Wallet_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Wallets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(45) NOT NULL,
  `message_date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Messages_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Deliveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Deliveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `delivery_status` ENUM('Delivered', 'In transit') NOT NULL,
  `user_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_has_Addresses_Addresses1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Addresses_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Addresses_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Addresses_Addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`SignIn_Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`SignIn_Options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loginid` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `faceid` ENUM('ON', 'OFF') NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SignIn_Options_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_SignIn_Options_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Heaven_Gebregiorgis`.`Feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Heaven_Gebregiorgis`.`Feedbacks` (
  `id` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `star_rate` INT NULL,
  `review` MULTILINESTRING NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_has_Products_Products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Products_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Products_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Products_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Heaven_Gebregiorgis`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
